### ISSUE TITLE
Searching tags to add crashes app

### ISSUE THREAD

**Issue by neopostmodern** [neopostmodern/structure#161]
New bug in 0.20.2

```
Here is a technical summary of the error caught by React error boundary:

Cannot read properties of undefined (reading 'toLowerCase')
TypeError: Cannot read properties of undefined (reading 'toLowerCase')
    at https://structure.neopostmodern.com/main.58ffc25d187ca4d409cf.js:1:55706
    at Array.map (<anonymous>)
    at https://structure.neopostmodern.com/main.58ffc25d187ca4d409cf.js:1:55647
    at Object.Ka [as useMemo] (https://structure.neopostmodern.com/vendors.dcf7b755f6741d088736.js:152:304994)
    at t.useMemo (https://structure.neopostmodern.com/vendors.dcf7b755f6741d088736.js:152:394956)
    at ga (https://structure.neopostmodern.com/main.58ffc25d187ca4d409cf.js:1:55607)
    at Sa (https://structure.neopostmodern.com/vendors.dcf7b755f6741d088736.js:152:300613)
    at _s (https://structure.neopostmodern.com/vendors.dcf7b755f6741d088736.js:152:312244)
    at kl (https://structure.neopostmodern.com/vendors.dcf7b755f6741d088736.js:152:358434)
    at yu (https://structure.neopostmodern.com/vendors.dcf7b755f6741d088736.js:152:346549)
```

**Comment by neopostmodern** [comment]
Failed to reproduce and was solved by clearing the cache – closing for now.

**Comment by neopostmodern** [comment]
Happened again on a device that previously could add tags, so maybe it's a timing issue?

Source code, error happens in line 6 (`index: n.toLowerCase()...`)
```
                        return "loading" === r ? [] : s ? r.map((function(e) {
                            var t = e._id
                              , n = e.name;
                            return {
                                _id: t,
                                index: n.toLowerCase().indexOf(s.toLowerCase()),
                                name: n
                            }
                        }
                        )).filter((function(e) {
                            return -1 !== e.index
                        }
                        )).sort((function(e, t) {
                            return e.index + e.name.length / 100 - (t.index + t.name.length / 100)
                        }
                        )).map((function(e) {
                            var t = e._id;
                            return v[t]
                        }
                        )) : r
```
