### ISSUE TITLE
Status page: Backend health check does not detect database outage

### ISSUE THREAD

**Issue by neopostmodern** [neopostmodern/structure#243]
When using the actual application I got
```
Error: Error finding [...]: connect ECONNREFUSED 127.0.0.1:27017
    at /home/structure/backend/server/node_modules/connect-mongodb-session/index.js:136:21
    at /home/structure/backend/server/node_modules/mongodb/lib/utils.js:349:66
```
while the status page said the backend health check was fine (it should connect to the DB though).
MongoDB was most likely down at this moment.

**Comment by neopostmodern** [comment]
For some reason the `/hello` endpoint responds differently depending on whether you're logged in or not. If you're not logged in (as the monitoring system is) it will *always* return "OK" (200), even when the DB is down.

**Comment by neopostmodern** [comment]
Couldn't reproduce locally
